version: '3.3'
services:
  database:
    image: mysql:5.7
    volumes:
        - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - back

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - back

  wordpress:
    depends_on:
      - database
    image: skilfulll1/wordpress:latest
    restart: always
    working_dir: /var/www/html
    volumes:
      - wordpress:/var/www/html/wp-content:rw
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 80:80
      - 443:443
    networks:
      - back

volumes:
  cicddockerhubwordpress_database:
    external: true
  cicddockerhubwordpress_wordpress:
    external: true

networks:
  back:
